spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:box
    username: Lester
    password: Lester
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
server:
  port: 9001
